# Generated by Django 2.1.5 on 2019-10-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menuitems',
            fields=[
                ('menuorder', models.IntegerField(primary_key=True, serialize=False)),
                ('menualias', models.CharField(max_length=255)),
                ('menutitle', models.CharField(max_length=255)),
                ('menusubtitle', models.CharField(max_length=255)),
                ('menuapi', models.CharField(max_length=255)),
                ('menuisreport', models.IntegerField()),
            ],
            options={
                'db_table': 'menuitems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('vdate', models.DateTimeField()),
                ('ddate', models.CharField(max_length=10)),
                ('particulars', models.CharField(max_length=255)),
                ('vchtype', models.CharField(max_length=255)),
                ('voucher_no', models.CharField(max_length=255)),
                ('recpay', models.CharField(max_length=255)),
                ('orig_vch', models.CharField(max_length=255)),
                ('uniquekey', models.BigIntegerField(primary_key=True, serialize=False)),
                ('credit', models.CharField(max_length=255)),
                ('debit', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockoutward',
            fields=[
                ('vdate', models.DateTimeField()),
                ('vouchertype', models.CharField(max_length=255)),
                ('voucher_no', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('party_ac', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('qty', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=255)),
                ('uniquekey', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'stock_outward',
                'managed': False,
            },
        ),
    ]
